layout_spectrum: 1
typography_spectrum: 0.2013963
color:
  saturation: 0
  lightness: 0
  brandStrength: 0.63008
  rhythmicContrast: 1
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: Adrián Blog
